//! Brainprint runtime engine implementation.

#[cfg(test)]
mod acceptance_coverage;
pub mod calls;
pub mod component;
pub mod config;
pub mod coverage;
pub mod db;
pub mod discovery;
pub mod domain;
pub mod evidence;
pub mod extract;
pub mod gaps;
pub mod generation;
pub mod graph;
pub mod graph_lifecycle;
pub mod identity;
pub mod impact;
pub mod imports;
pub mod init;
pub mod inspect;
pub mod lsp;
pub mod merge;
pub mod parser;
pub mod paths;
pub mod prepare;
pub mod python_semantic;
pub mod query;
pub mod reconcile;
pub mod refresh;
pub mod registry;
pub mod related_tests;
pub mod relations;
pub mod resolution;
pub mod resource;
pub mod runtime;
pub mod scan;
pub mod schema;
pub mod search;
pub mod semantic;
pub mod semantic_index;
pub mod structural;
pub mod symbol;
pub mod telemetry;
pub mod types;
pub mod typescript_semantic;
pub mod watch;
